# Shell variables
# Generated by 'wal'
wallpaper="/home/jmkwrld/Wallpapers/catgirl.jpg"

# Special
background='#190000'
foreground='#c3c1c1'
cursor='#c3c1c1'

# Colors
color0='#190000'
color1='#c1a500'
color2='#db007c'
color3='#d6bb00'
color4='#fca700'
color5='#ff601a'
color6='#ffc525'
color7='#968c8c'
color8='#c00000'
color9='#ffcc02'
color10='#ff269f'
color11='#ffe81f'
color12='#fec552'
color13='#ffa579'
color14='#ffdb88'
color15='#c3c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
