--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jmkwrld/Wallpapers/catgirl.jpg"

-- Special
background="#190000"
foreground="#c3c1c1"
cursor="#c3c1c1"

-- Colors
color0="#190000"
color1="#c1a500"
color2="#db007c"
color3="#d6bb00"
color4="#fca700"
color5="#ff601a"
color6="#ffc525"
color7="#968c8c"
color8="#c00000"
color9="#ffcc02"
color10="#ff269f"
color11="#ffe81f"
color12="#fec552"
color13="#ffa579"
color14="#ffdb88"
color15="#c3c1c1"
